### ISSUE TITLE
Code Cleanup: JS idioms, code style, etc

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/recipes-flux#11]
On brief inspection, we still need a lot of cleanup:

### Automated (?) (JsCs, JsHint)

* [x] Line length (80 or 100).
* [x] Newlines at end of file.

### Manual

* [x] Adding readability constructs like newlines between some functions
* [x] Idiomatic JS comments like: 
```js
/**
 * Foo
 */
```
  and not
```js
/**
Foo
 */
```

### Done

Stuff already done:

* ~~Spacing idioms `function () {}` not `function() {}`~~ (JSXCS)
* ~~Two spaces indentation~~ (JSXCS)

**Comment by aykayen** [comment]
Implemented in https://github.com/FormidableLabs/recipes-flux/pull/17
