### ISSUE TITLE
Eslint: Lint *all* the code.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/recipes-flux#16]
Switch to eslint with full JSX support!

TASK:

* Switch to eslint per `notes-react-exoskeleton` repo.
* Remove **all** `jshint` declarations
* Add new `eslint(-*|)` comment directives as applicable.

**Comment by colinmegill** [comment]
Agreed. On it.

**Comment by ryan-roemer** [comment]
@colinmegill -- See https://github.com/FormidableLabs/notes-react-exoskeleton/pull/4 for a full implementation switching over to eslint. Should be good to go for this repo now.

**Comment by colinmegill** [comment]
Awesome - great work. cc @aykayen

**Comment by aykayen** [comment]
Implemented in https://github.com/FormidableLabs/recipes-flux/pull/17
