### ISSUE TITLE
Fluxxor or Vanilla flux implementation

### ISSUE THREAD

**Issue by colinmegill** [FormidableLabs/recipes-flux#6]
Reflux is nice. It has a lot of nice abstractions for teaching that will allow me to say things like "ok now let's have the component listen to the store" and it's as easy as adding a mixin. "Ok now let's have the store listen to an action" is just a method. 

But these are all just callbacks - there's no reason we couldn't implement our own version of flux, and probably will want to - possibly even on a per project basis if we decide to adopt the pattern. 

My first reaction is that flux uses closures very effectively and that that complements what react does. 

Here's a useful resource for vanilla flux: https://speakerdeck.com/fisherwebdev/flux-meetup

**Comment by ryan-roemer** [comment]
@colinmegill -- Is this issue still relevant now that we've got McFly? Please close if so.
