### ISSUE TITLE
HTTP 

### ISSUE THREAD

**Issue by colinmegill** [FormidableLabs/recipes-flux#7]
Dale & Colin talk about HTTP strategy

**Comment by colinmegill** [comment]
https://www.npmjs.com/package/lowdb

**Comment by colinmegill** [comment]
This is coming together now. Since we're using McFly, we'll trigger HTTP in the action and return a promise. This allows for optimistic updates (store triggers change and components rerender) and then if the promise rejects, you append *not saved* to the element in the interface, if it resolves and is _different_ than the contents of the store, the store fires a change event and the ui rerenders as usual. 

Of course, if the promise returns and nukes the store and the server side copy is identical to the client side copy, there is no change. Check @kenwheeler?

**Comment by kenwheeler** [comment]
If the state is identical you can prevent rerender with PureRenderMixin
